### ISSUE TITLE
Mac OS El Capitan

### ISSUE THREAD

**Issue by next2non** [kopurando/virga.app-youtube-dl-GUI-for-OS-X#1]
The virga app not working properly under "El Capitan", the popup box that asks for input e.g. video only, Mp3 only or both is not appearing. It starts downloading without the popup.

**Comment by kopurando** [comment]
i confirm, will have a look at it during weekend, thanks!

**Comment by next2non** [comment]
Thanks

**Comment by kopurando** [comment]
Fixed, https://github.com/kopurando/youtube-dl-GUI/releases/tag/1.0.2
Thank you!
