### ISSUE TITLE
Warn when going to download more than 1 link & File renaming

### ISSUE THREAD

**Issue by jllodra** [kopurando/virga.app-youtube-dl-GUI-for-OS-X#2]
Hi,

superb work, you earned the hall of fame after having coded something like this in AppleScript... :)

I have 2 suggestions:
- The program could warn the user when going to download more than 1 link because downloads are unstoppable... Just a "Are you sure?" message would be ok.
- I see downloaded files are like "Title - youtube_xxx._" or "Title - soundlcloud_xxx._", I think that there is no actual reason to keep the "- yotube_xxx" suffixes. This will save me from manually rewrite the files.

Thanks!

**Comment by kopurando** [comment]
Hey,
Thanks for your feedback, I'm  glad the app comes useful!

 — In case of multiple items download there's a "Cancel" button, to prevent downloading, I see it as an equivalent to an extra dialogue window... Have you had issues clicking wrong button on this selector?
![screen](https://dl.dropboxusercontent.com/u/3635046/nert.png)

 — Suffixes I decided to keep for a reason, in case I need to locate the media online later... as some are downloaded from youtube, some from dailymotion etc, and sometimes I need to re-download them, and knowing exact media ID helps here a lot. I can see how it bothers some people, so an extra checkbox "add ID suffixes" can help here, but I am not certain whether it's doable via AppleScript. Once more, rewriting the whole thing in Python would be a great idea :)

**Comment by jllodra** [comment]
Hi again,

thanks for the answer.
- I can't see this dialogue when downloading multiple songs from Soundcloud, try this link https://soundcloud.com/armadamusic/sets/armin-van-buuren-universal that contains 4 songs. In my case, it starts downloading but without any dialogue. Anyway, this is not a big problem.
- No problem with the suffix thing, I get your point.

Best

**Comment by kopurando** [comment]
Thanks, you made a good point! Audio-only playlists were not showing a format-selection dialogue, hence user did not have a chance to cancel downloading. Release 1.0.4 fixes that, please download here:
https://github.com/kopurando/virga.app-youtube-dl-GUI-for-OS-X/releases/tag/1.0.4

https://www.dropbox.com/s/6d3nt0zk3mnv33m/armin.png?dl=0
