### ISSUE TITLE
Ask for Download location

### ISSUE THREAD

**Issue by username1290** [kopurando/virga.app-youtube-dl-GUI-for-OS-X#4]
Hi, where are files downloaded? An option for a donwload location or ask for default location would help.

**Comment by kopurando** [comment]
Hello,
As per readme:
Files are downloaded into your _Downloads/from youtube and others/_ folder.


I thought it'd be better to have downloads in a separate folder. You can change the default folder here:`
virga barebone.app/Contents/Resources/Scripts/virga.scptd/Contents/Resources/Scripts/main.scpt`
line 3:
`set downloadsFolder to "Downloads/from youtube and others/"
`

**Comment by username1290** [comment]
Ah! sorry, thanks a lot
